export const dummyCinemas = [
  {
    id: 1,
    name: "Cinema 1",
    shows: [
      {
        id: 101,
        movieName: "Avatar",
        startTime: "12:00",
        duration: "2h 42m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 102,
        movieName: "Inception",
        startTime: "15:30",
        duration: "2h 28m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 103,
        movieName: "The Dark Knight",
        startTime: "18:30",
        duration: "2h 32m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 104,
        movieName: "Jurassic Park",
        startTime: "21:15",
        duration: "2h 7m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 105,
        movieName: "Titanic",
        startTime: "13:45",
        duration: "3h 14m",
        format: "3D",
        ticketPrice: 13.99,
      },
      {
        id: 106,
        movieName: "The Avengers",
        startTime: "16:00",
        duration: "2h 23m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 107,
        movieName: "Toy Story",
        startTime: "19:00",
        duration: "1h 21m",
        format: "2D",
        ticketPrice: 8.99,
      },
      {
        id: 108,
        movieName: "The Matrix",
        startTime: "22:30",
        duration: "2h 16m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 109,
        movieName: "Frozen",
        startTime: "14:15",
        duration: "1h 42m",
        format: "3D",
        ticketPrice: 11.99,
      },
      {
        id: 110,
        movieName: "The Shawshank Redemption",
        startTime: "17:45",
        duration: "2h 22m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 111,
        movieName: "Pulp Fiction",
        startTime: "20:30",
        duration: "2h 34m",
        format: "2D",
        ticketPrice: 11.99,
      },
      {
        id: 112,
        movieName: "E.T. the Extra-Terrestrial",
        startTime: "13:00",
        duration: "2h 1m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 113,
        movieName: "The Lion King",
        startTime: "16:30",
        duration: "1h 29m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 114,
        movieName: "Forrest Gump",
        startTime: "19:45",
        duration: "2h 22m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      // Add more movies for Cinema 1
      // ...
    ],
  },
  {
    id: 2,
    name: "Cinema 2",
    shows: [
      {
        id: 101,
        movieName: "Avatar",
        startTime: "12:00",
        duration: "2h 42m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 102,
        movieName: "Inception",
        startTime: "15:30",
        duration: "2h 28m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 103,
        movieName: "The Dark Knight",
        startTime: "18:30",
        duration: "2h 32m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 104,
        movieName: "Jurassic Park",
        startTime: "21:15",
        duration: "2h 7m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 105,
        movieName: "Titanic",
        startTime: "13:45",
        duration: "3h 14m",
        format: "3D",
        ticketPrice: 13.99,
      },
      {
        id: 106,
        movieName: "The Avengers",
        startTime: "16:00",
        duration: "2h 23m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 107,
        movieName: "Toy Story",
        startTime: "19:00",
        duration: "1h 21m",
        format: "2D",
        ticketPrice: 8.99,
      },
      {
        id: 108,
        movieName: "The Matrix",
        startTime: "22:30",
        duration: "2h 16m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 109,
        movieName: "Frozen",
        startTime: "14:15",
        duration: "1h 42m",
        format: "3D",
        ticketPrice: 11.99,
      },
      {
        id: 110,
        movieName: "The Shawshank Redemption",
        startTime: "17:45",
        duration: "2h 22m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 111,
        movieName: "Pulp Fiction",
        startTime: "20:30",
        duration: "2h 34m",
        format: "2D",
        ticketPrice: 11.99,
      },
      {
        id: 112,
        movieName: "E.T. the Extra-Terrestrial",
        startTime: "13:00",
        duration: "2h 1m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 113,
        movieName: "The Lion King",
        startTime: "16:30",
        duration: "1h 29m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 114,
        movieName: "Forrest Gump",
        startTime: "19:45",
        duration: "2h 22m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      // Add more movies for Cinema 1
      // ...
    ],
  },
  {
    id: 3,
    name: "Cinema 3",
    shows: [
      {
        id: 101,
        movieName: "Avatar",
        startTime: "12:00",
        duration: "2h 42m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 102,
        movieName: "Inception",
        startTime: "15:30",
        duration: "2h 28m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 103,
        movieName: "The Dark Knight",
        startTime: "18:30",
        duration: "2h 32m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 104,
        movieName: "Jurassic Park",
        startTime: "21:15",
        duration: "2h 7m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 105,
        movieName: "Titanic",
        startTime: "13:45",
        duration: "3h 14m",
        format: "3D",
        ticketPrice: 13.99,
      },
      {
        id: 106,
        movieName: "The Avengers",
        startTime: "16:00",
        duration: "2h 23m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 107,
        movieName: "Toy Story",
        startTime: "19:00",
        duration: "1h 21m",
        format: "2D",
        ticketPrice: 8.99,
      },
      {
        id: 108,
        movieName: "The Matrix",
        startTime: "22:30",
        duration: "2h 16m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 109,
        movieName: "Frozen",
        startTime: "14:15",
        duration: "1h 42m",
        format: "3D",
        ticketPrice: 11.99,
      },
      {
        id: 110,
        movieName: "The Shawshank Redemption",
        startTime: "17:45",
        duration: "2h 22m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 111,
        movieName: "Pulp Fiction",
        startTime: "20:30",
        duration: "2h 34m",
        format: "2D",
        ticketPrice: 11.99,
      },
      {
        id: 112,
        movieName: "E.T. the Extra-Terrestrial",
        startTime: "13:00",
        duration: "2h 1m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 113,
        movieName: "The Lion King",
        startTime: "16:30",
        duration: "1h 29m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 114,
        movieName: "Forrest Gump",
        startTime: "19:45",
        duration: "2h 22m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      // Add more movies for Cinema 1
      // ...
    ],
  },
  {
    id: 4,
    name: "Cinema 4",
    shows: [
      {
        id: 101,
        movieName: "Avatar",
        startTime: "12:00",
        duration: "2h 42m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 102,
        movieName: "Inception",
        startTime: "15:30",
        duration: "2h 28m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 103,
        movieName: "The Dark Knight",
        startTime: "18:30",
        duration: "2h 32m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 104,
        movieName: "Jurassic Park",
        startTime: "21:15",
        duration: "2h 7m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 105,
        movieName: "Titanic",
        startTime: "13:45",
        duration: "3h 14m",
        format: "3D",
        ticketPrice: 13.99,
      },
      {
        id: 106,
        movieName: "The Avengers",
        startTime: "16:00",
        duration: "2h 23m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 107,
        movieName: "Toy Story",
        startTime: "19:00",
        duration: "1h 21m",
        format: "2D",
        ticketPrice: 8.99,
      },
      {
        id: 108,
        movieName: "The Matrix",
        startTime: "22:30",
        duration: "2h 16m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 109,
        movieName: "Frozen",
        startTime: "14:15",
        duration: "1h 42m",
        format: "3D",
        ticketPrice: 11.99,
      },
      {
        id: 110,
        movieName: "The Shawshank Redemption",
        startTime: "17:45",
        duration: "2h 22m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 111,
        movieName: "Pulp Fiction",
        startTime: "20:30",
        duration: "2h 34m",
        format: "2D",
        ticketPrice: 11.99,
      },
      {
        id: 112,
        movieName: "E.T. the Extra-Terrestrial",
        startTime: "13:00",
        duration: "2h 1m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 113,
        movieName: "The Lion King",
        startTime: "16:30",
        duration: "1h 29m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 114,
        movieName: "Forrest Gump",
        startTime: "19:45",
        duration: "2h 22m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      // Add more movies for Cinema 1
      // ...
    ],
  },
  {
    id: 5,
    name: "Cinema 5",
    shows: [
      {
        id: 101,
        movieName: "Avatar",
        startTime: "12:00",
        duration: "2h 42m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 102,
        movieName: "Inception",
        startTime: "15:30",
        duration: "2h 28m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 103,
        movieName: "The Dark Knight",
        startTime: "18:30",
        duration: "2h 32m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 104,
        movieName: "Jurassic Park",
        startTime: "21:15",
        duration: "2h 7m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 105,
        movieName: "Titanic",
        startTime: "13:45",
        duration: "3h 14m",
        format: "3D",
        ticketPrice: 13.99,
      },
      {
        id: 106,
        movieName: "The Avengers",
        startTime: "16:00",
        duration: "2h 23m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
      {
        id: 107,
        movieName: "Toy Story",
        startTime: "19:00",
        duration: "1h 21m",
        format: "2D",
        ticketPrice: 8.99,
      },
      {
        id: 108,
        movieName: "The Matrix",
        startTime: "22:30",
        duration: "2h 16m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 109,
        movieName: "Frozen",
        startTime: "14:15",
        duration: "1h 42m",
        format: "3D",
        ticketPrice: 11.99,
      },
      {
        id: 110,
        movieName: "The Shawshank Redemption",
        startTime: "17:45",
        duration: "2h 22m",
        format: "2D",
        ticketPrice: 10.99,
      },
      {
        id: 111,
        movieName: "Pulp Fiction",
        startTime: "20:30",
        duration: "2h 34m",
        format: "2D",
        ticketPrice: 11.99,
      },
      {
        id: 112,
        movieName: "E.T. the Extra-Terrestrial",
        startTime: "13:00",
        duration: "2h 1m",
        format: "3D",
        ticketPrice: 12.99,
      },
      {
        id: 113,
        movieName: "The Lion King",
        startTime: "16:30",
        duration: "1h 29m",
        format: "2D",
        ticketPrice: 9.99,
      },
      {
        id: 114,
        movieName: "Forrest Gump",
        startTime: "19:45",
        duration: "2h 22m",
        format: "IMAX",
        ticketPrice: 14.99,
      },
    ],
  },
];
